### PR TITLE
Issue#16 comments

### PR DESCRIPTION
**Pull request by OnesQuared**
Honestly not 100% sure about the comments, so bare minimum at the moment, let me know if its wrong or want it worded differently or more.

### CODE REVIEW

**Comment by ThomasJayWilliams** [comment]
Wow, didn't expect anyone to be interested in this. Thanks. I'll check it out later.  Tommorrov, I guess.

**Comment by OnesQuared** [comment]
Made the changes, hopefully correct, my apologizes for the mistakes, using this as more of a learning experience in terms of codes

**Comment by ThomasJayWilliams** [comment]
Alright, looks like you've got the point. Good job and thanks for helping.

**Comment by ThomasJayWilliams** [comment]
Also, if you want I can add more simple issues that you could help me with.

**Comment by OnesQuared** [comment]
Hopefully I can be of help, but if you are willing I can attempt some simple ones

**Comment by ThomasJayWilliams** [comment]
Check your collaboration requests. When you'll accept it Ill be able assign issues on you.

**Comment by ThomasJayWilliams** [comment]
Nice. And before you started - for your issue create separate branch with issue number and short name of it. After you'll finish with task send merge request. Example: branch "Issue#512_Tree_Implementation" (git doesn't allow to use spaces in branch names).

**Comment by OnesQuared** [comment]
alright, I'll see what I can do

**Comment by ThomasJayWilliams** [comment]
Sweet. Thanks for your help again.

**Pull request merged**
