### PR TITLE
Issue #26 add missing crud to element tree

### PR DESCRIPTION
**Pull request by OnesQuared**
Not 100% sure if these are the kind that are needed, mostly create was a bit of a gamble.

### CODE REVIEW

**Comment by ThomasJayWilliams** [comment]
Alright, I guess I'll check it later or either tomorrow. Today I have huge amount of work to do.

**Comment by ThomasJayWilliams** [comment]
Alright, this is good enough. I'll provide some refactoring first, then I'll merge branch. For now there are no tasks for you and I would be able to add new ones today is for sure. I guess I'll add new issues for you tomorrow.

**Comment by OnesQuared** [comment]
alright, no need to rush out to make issues, just put some out when you have the time. I'll be checking in time to time

**Comment by ThomasJayWilliams** [comment]
Check out last commit. I've left some comments about changes.

**Comment by ThomasJayWilliams** [comment]
So, dude, I removed you from collaborators for now. The current state of SDML.NET is "paused". I decided to develop standard for it first, and then, after it will be ready I will continue develop library. Thanks for help, you did a good job.

**Pull request merged**
