### PR TITLE
Issue#28 rename SDML to sdml

### PR DESCRIPTION
**Pull request by OnesQuared**
The latest commit should have most of the project, apologizes for making multiple commits prior. Hopefully I didn't screw anything up. Let me know if any changes are needed

### CODE REVIEW

**Comment by OnesQuared** [comment]
I'm using visual studio code for this at the moment, but it seems the file names didn't change even though I did so in the code, maybe I'll switch over to visual studio. Not sure how the project name changed, but I'll change it back to the capitals.

**Comment by ThomasJayWilliams** [comment]
Sweet.

By the way, the fact you're using Visual Code explains something - the solution doesn't build. You should always build solution to be sure that solution is working and nothing broken. It is crucial to do not push into repository broken project.

Anyway, I guess I'll check request tomorrow, if you'll finish.

**Comment by OnesQuared** [comment]
Alright, I'll try and figure things out with studio since code seems to be a bit of a problem. I'll see what I can do tonight, if not tomorrow afternoon probably.

**Comment by ThomasJayWilliams** [comment]
Sounds awesome, thanks for spending time on this project.

Oh, almost forgot - if you will continue working on issue change the label to in progress. This may seem a bit annoying, but in enterprise projects you will forced to do things like this. So it's a lot easier to form a habit now.

**Comment by OnesQuared** [comment]
So according to [This](https://github.com/desktop/desktop/issues/2672#issuecomment-329011490), there is problem with lower and upper case in file names. So I made a new [pull request](https://github.com/ThomasJayWilliams/SDML.NET/pull/32) by forking the repository and reuploading all the name class and file name changes to apply. Not sure if it will actually work, but trying to merge into the issue #28 branch to see if it works or not

**Pull request closed without merging**
